- name: Install Windows Updates
  hosts: windows
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
